--------USUARIOS------------------------------------------------------------------------------
EXECUTE NUEVO_USUARIO('DNI1', 'NOMBRE1', 'AP1', 'OB1', 'CN1','MI1','EP1','EM1',1,1 );
EXECUTE NUEVO_USUARIO('DNI2', 'NOMBRE2', 'AP2', 'OB2', 'CN2','MI2','EP2','EM2',2,2 );
EXECUTE NUEVO_USUARIO('DNI3', 'NOMBRE3', 'AP3', 'OB3', 'CN3','MI3','EP3','EM3',3,3 );
EXECUTE NUEVO_USUARIO('DNI4', 'NOMBRE4', 'AP4', 'OB4', 'CN4','MI4','EP4','EM4',4,4 );

INSERT INTO USUARIOS(DNI,NOMBRE, APELLIDOS, OBSERVACIONES, CONTACTO, MOTIVO_INGRESO, ESTADO_PSICOLOGICO, 
	ESTADO_MEDICO, SANCIONES, PREMIOS)
VALUES ('DNI1', 'NOMBRE1', 'AP1', 'OB1', 'CN1','MI1','EP1','EM1',1,1);

INSERT INTO USUARIOS(DNI,NOMBRE, APELLIDOS, OBSERVACIONES, CONTACTO, MOTIVO_INGRESO, ESTADO_PSICOLOGICO, 
	ESTADO_MEDICO, SANCIONES, PREMIOS)
VALUES ('DNI2', 'NOMBRE2', 'AP2', 'OB2', 'CN2','MI2','EP2','EM2',2,2);

INSERT INTO USUARIOS(DNI,NOMBRE, APELLIDOS, OBSERVACIONES, CONTACTO, MOTIVO_INGRESO, ESTADO_PSICOLOGICO, 
	ESTADO_MEDICO, SANCIONES, PREMIOS)
VALUES ('DNI3', 'NOMBRE3', 'AP3', 'OB3', 'CN3','MI3','EP3','EM3',3,3);

INSERT INTO USUARIOS(DNI,NOMBRE, APELLIDOS, OBSERVACIONES, CONTACTO, MOTIVO_INGRESO, ESTADO_PSICOLOGICO, 
	ESTADO_MEDICO, SANCIONES, PREMIOS)
VALUES ('DNI4', 'NOMBRE4', 'AP4', 'OB4', 'CN4','MI4','EP4','EM4',4,4);
-------------------------------------------UNIDADES--------------------------------------------------
EXECUTE NUEVA_UNIDAD('COD1', 'E1' );
EXECUTE NUEVA_UNIDAD('COD2', 'E2' );
EXECUTE NUEVA_UNIDAD('COD3', 'E3' );
EXECUTE NUEVA_UNIDAD('COD4', 'E4' );


INSERT INTO UNIDADES(OID_PRE,OID_MPR, CODIGO_IDENTIFICACION, ESTADO_EJEMPLAR)
VALUES('COD1', 'E1');

INSERT INTO UNIDADES(OID_PRE,OID_MPR, CODIGO_IDENTIFICACION, ESTADO_EJEMPLAR)
VALUES('COD2', 'E2');


INSERT INTO UNIDADES(OID_PRE,OID_MPR, CODIGO_IDENTIFICACION, ESTADO_EJEMPLAR)
VALUES('COD3', 'E3');


INSERT INTO UNIDADES(OID_PRE,OID_MPR, CODIGO_IDENTIFICACION, ESTADO_EJEMPLAR)
VALUES('COD4', 'E4');

-----------------------PRESTAMOS------------------------------------------------------------------
EXECUTE NUEVO_PERSTAMO('DNI1', 'FI1', 'FF1','T', 'NE1' );
EXECUTE NUEVO_PRESTAMO('DNI2', 'FI2', 'FF2','F', 'NE2'  );
EXECUTE NUEVO_PRESTAMO('DNI3', 'FI3', 'FF3','T', 'NE3'  );
EXECUTE NUEVO_PRESTAMO('DNI4', 'FI4', 'FF4','F', 'NE4'  );

INSERT INTO PRESTAMOS(OID_PRE, DNI,FECHA_INICIO,FECHA_FIN,DEVOLUCION,NOMBRE_ENCARGADO)
VALUES ('DNI1', 'FI1', 'FF1','T', 'NE1');
INSERT INTO PRESTAMOS(OID_PRE, DNI,FECHA_INICIO,FECHA_FIN,DEVOLUCION,NOMBRE_ENCARGADO)
VALUES ('DNI2', 'FI2', 'FF2','F', 'NE2' );
INSERT INTO PRESTAMOS(OID_PRE, DNI,FECHA_INICIO,FECHA_FIN,DEVOLUCION,NOMBRE_ENCARGADO)
VALUES ('DNI3', 'FI3', 'FF3','T', 'NE3' );
INSERT INTO PRESTAMOS(OID_PRE, DNI,FECHA_INICIO,FECHA_FIN,DEVOLUCION,NOMBRE_ENCARGADO)
VALUES ('DNI4', 'FI4', 'FF4','F', 'NE4' );

----------------------------------------MATERIAL_PRESTADO-----------------------------------------------
EXECUTE NUEVO_MATERIAL_PRESTADO('N1', 'D1', 'T',1, 'T1' );
EXECUTE NUEVO_MATERIAL_PRESTADO('N2', 'D2', 'F',2, 'T2'  );
EXECUTE NUEVO_MATERIAL_PRESTADO('N3', 'D3', 'T',3, 'T3'  );
EXECUTE NUEVO_MATERIAL_PRESTADO('N4', 'D4', 'F',4, 'T4'  );

INSERT INTO MATERIALES_PRESTADOS(OID_MPR,NOMBRE,DISPONIBILIDAD,ESTADO_DEVOLUCION,CANTIDAD,TIPO)
VALUES('N1', 'D1', 'T',1, 'T1');
INSERT INTO MATERIALES_PRESTADOS(OID_MPR,NOMBRE,DISPONIBILIDAD,ESTADO_DEVOLUCION,CANTIDAD,TIPO)
VALUES('N2', 'D2', 'F',2, 'T2');
INSERT INTO MATERIALES_PRESTADOS(OID_MPR,NOMBRE,DISPONIBILIDAD,ESTADO_DEVOLUCION,CANTIDAD,TIPO)
VALUES('N3', 'D3', 'T',3, 'T3');
INSERT INTO MATERIALES_PRESTADOS(OID_MPR,NOMBRE,DISPONIBILIDAD,ESTADO_DEVOLUCION,CANTIDAD,TIPO)
VALUES('N4', 'D4', 'F',4, 'T4');


---------------------------INSCRIPCIONES--------------------------------------------------------------
EXECUTE NUEVA_INSCRIPCION('DNI1', 'F1', 'C1');
EXECUTE NUEVA_INSCRIPCION('DNI2', 'F2', 'C2'  );
EXECUTE NUEVA_INSCRIPCION('DNI3', 'F3', 'C3' );
EXECUTE NUEVA_INSCRIPCION('DNI4', 'F4', 'C4' );

INSERT INTO INSCRIPCIONES(OID_INS, DNI, OID_ACT, FECHA, CORREO_ELECTRONICO)
VALUES('DNI1', 'F1', 'C1');
INSERT INTO INSCRIPCIONES(OID_INS, DNI, OID_ACT, FECHA, CORREO_ELECTRONICO)
VALUES('DNI2', 'F2', 'C2');
INSERT INTO INSCRIPCIONES(OID_INS, DNI, OID_ACT, FECHA, CORREO_ELECTRONICO)
VALUES('DNI3', 'F3', 'C3');
INSERT INTO INSCRIPCIONES(OID_INS, DNI, OID_ACT, FECHA, CORREO_ELECTRONICO)
VALUES('DNI4', 'F4', 'C4');

-------------------------------------------INFORMES-------------------------------------------------------
EXECUTE NUEVO_INFORME('DN1', 'T1', 'R1', 'F1', 'L1', 'OB1');
EXECUTE NUEVO_INFORME('DN2', 'T2', 'R2', 'F2', 'L2', 'OB2' );
EXECUTE NUEVO_INFORME('DN3', 'T3', 'R3', 'F3', 'L3', 'OB3' );
EXECUTE NUEVO_INFORME('DN4', 'T4', 'R4', 'F4', 'L4', 'OB4');

INSERT INTO INFORMES(OID_INF,OID_CM,DNI,TIPO,RESPONSABLE,FECHA,LUGAR,OBSERVACIONES)
VALUES('DN1', 'T1', 'R1', 'F1', 'L1', 'OB1');
INSERT INTO INFORMES(OID_INF,OID_CM,DNI,TIPO,RESPONSABLE,FECHA,LUGAR,OBSERVACIONES)
VALUES('DN2', 'T2', 'R2', 'F2', 'L2', 'OB2');
INSERT INTO INFORMES(OID_INF,OID_CM,DNI,TIPO,RESPONSABLE,FECHA,LUGAR,OBSERVACIONES)
VALUES('DN3', 'T3', 'R3', 'F3', 'L3', 'OB3' );
INSERT INTO INFORMES(OID_INF,OID_CM,DNI,TIPO,RESPONSABLE,FECHA,LUGAR,OBSERVACIONES)
VALUES('DN4', 'T4', 'R4', 'F4', 'L4', 'OB4' );

----------------------------------------ESTANCIAS-------------------------------------------------------
EXECUTE NUEVA_ESTANCIA('DN1', 'FE1', 'FS1');
EXECUTE NUEVA_ESTANCIA('DN2', 'FE2', 'FS2' );
EXECUTE NUEVA_ESTANCIA('DN3', 'FE3', 'FS3' );
EXECUTE NUEVA_ESTANCIA('DN4', 'FE4', 'FS4');

INSERT INTO ESTANCIAS (OID_EST,DNI,OID_ALJ,FECHA_ENTRADA,FECHA_SALIDA)
VALUES('DN1', 'FE1', 'FS1');
INSERT INTO ESTANCIAS (OID_EST,DNI,OID_ALJ,FECHA_ENTRADA,FECHA_SALIDA)
VALUES('DN2', 'FE2', 'FS2');
INSERT INTO ESTANCIAS (OID_EST,DNI,OID_ALJ,FECHA_ENTRADA,FECHA_SALIDA)
VALUES('DN3', 'FE3', 'FS3');
INSERT INTO ESTANCIAS (OID_EST,DNI,OID_ALJ,FECHA_ENTRADA,FECHA_SALIDA)
VALUES('DN4', 'FE4', 'FS4');

-----------------------------------CITAS_MEDICAS---------------------------------------------------
EXECUTE NUEVA_CITA_MEDICA('DN1', 'DOC1', 'F1','L1');
EXECUTE NUEVA_CITA_MEDICA('DN2', 'DOC2', 'F2','L2');
EXECUTE NUEVA_CITA_MEDICA('DN3', 'DOC3', 'F3','L3' );
EXECUTE NUEVA_CITA_MEDICA('DN4', 'DOC4', 'F4','L4');

INSERT INTO CITAS_MEDICAS(OID_CM,DNI,DOCTOR,FECHA,LUGAR)
VALUES('DN1', 'DOC1', 'F1','L1');
INSERT INTO CITAS_MEDICAS(OID_CM,DNI,DOCTOR,FECHA,LUGAR)
VALUES('DN2', 'DOC2', 'F2','L2');
INSERT INTO CITAS_MEDICAS(OID_CM,DNI,DOCTOR,FECHA,LUGAR)
VALUES('DN3', 'DOC3', 'F3','L3');
INSERT INTO CITAS_MEDICAS(OID_CM,DNI,DOCTOR,FECHA,LUGAR)
VALUES('DN4', 'DOC4', 'F4','L4');

-----------------------------------ALOJAMIENTOS-----------------------------------------------
EXECUTE NUEVO_ALOJAMIENTO('U1', 'D1', 'R1',1, 1, 'T');
EXECUTE NUEVO_ALOJAMIENTO('U2', 'D2', 'R2',2, 2, 'F');
EXECUTE NUEVO_ALOJAMIENTO('U3', 'D3', 'R3',3, 3, 'T');
EXECUTE NUEVO_ALOJAMIENTO('U4', 'D4', 'R4',4, 4, 'F');

INSERT INTO ALOJAMIENTOS(OID_ALJ,UBICACION,DIRECCION,RESIDENTES,NUMERO_RESIDENTES,NUMERO_HABITACION,DISPONIBILIDAD)
VALUES('U1', 'D1', 'R1',1, 1, 'T');
INSERT INTO ALOJAMIENTOS(OID_ALJ,UBICACION,DIRECCION,RESIDENTES,NUMERO_RESIDENTES,NUMERO_HABITACION,DISPONIBILIDAD)
VALUES('U2', 'D2', 'R2',2, 2, 'F');
INSERT INTO ALOJAMIENTOS(OID_ALJ,UBICACION,DIRECCION,RESIDENTES,NUMERO_RESIDENTES,NUMERO_HABITACION,DISPONIBILIDAD)
VALUES('U3', 'D3', 'R3',3, 3, 'T');
INSERT INTO ALOJAMIENTOS(OID_ALJ,UBICACION,DIRECCION,RESIDENTES,NUMERO_RESIDENTES,NUMERO_HABITACION,DISPONIBILIDAD)
VALUES('U4', 'D4', 'R4',4, 4, 'F');

----------------------------------------------ACTIVIDADES------------------------------------------------
EXECUTE NUEVA_ACTIVIDAD('L1', 'F1', 1,'C1');
EXECUTE NUEVA_ACTIVIDAD('L2', 'F2', 2,'C2');
EXECUTE NUEVA_ACTIVIDAD('L3', 'F3', 3,'C3');
EXECUTE NUEVA_ACTIVIDAD('L4', 'F4', 4,'C4');

INSERT INTO ACTIVIDADES(OID_ACT,LUGAR,FECHA,NUMERO_ASISTENTES,CALIFICACIONES)
VALUES('L1', 'F1', 1,'C1');
INSERT INTO ACTIVIDADES(OID_ACT,LUGAR,FECHA,NUMERO_ASISTENTES,CALIFICACIONES)
VALUES('L2', 'F2', 2,'C2');
INSERT INTO ACTIVIDADES(OID_ACT,LUGAR,FECHA,NUMERO_ASISTENTES,CALIFICACIONES)
VALUES('L3', 'F3', 3,'C3');
INSERT INTO ACTIVIDADES(OID_ACT,LUGAR,FECHA,NUMERO_ASISTENTES,CALIFICACIONES)
VALUES('L4', 'F4', 4,'C4');


