DROP SEQUENCE SEC_OID_ACT;
CREATE SEQUENCE SEC_OID_ACT START WITH 1 INCREMENT BY 1;

/* DUAL: tabla que tiene oracle para probar funciones on hacer calculos rápidos*/
CREATE OR REPLACE TRIGGER NUEVO_OID_ACT
BEFORE INSERT ON ACTIVIDADES
FOR EACH ROW
 BEGIN 
    SELECT SEC_OID_ACT.NEXTVAL INTO :NEW.OID_ACT FROM DUAL;
 END NUEVO_OID_ACT;
 
DROP SEQUENCE SEC_OID_INS;
CREATE SEQUENCE SEC_OID_INS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER NUEVO_OID_INS
BEFORE INSERT ON INSCRIPCIONES
FOR EACH ROW
    BEGIN
            SELECT SEC_OID_INS.NEXTVAL INTO :NEW.OID_INS FROM DUAL;
END NUEVO_OID_INS;
    


DROP SEQUENCE SEC_OID_CM;
CREATE SEQUENCE SEC_OID_CM START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER NUEVO_OID_CM
BEFORE INSERT ON CITAS_MEDICAS
FOR EACH ROW
    BEGIN 
        SELECT SEC_OID_CM.NEXTVAL INTO :NEW.OID_CM FROM DUAL;
END NUEVO_OID_CM;



DROP SEQUENCE SEC_OID_INF;
CREATE SEQUENCE SEC_OID_INF START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER NUEVO_OID_INF
BEFORE INSERT ON INFORMES
FOR EACH ROW
    BEGIN
        SELECT SEC_OID_INF.NEXTVAL INTO :NEW.OID_INF FROM DUAL;
END NUEVO_OID_INF;


DROP SEQUENCE SEC_OID_PRE;
CREATE SEQUENCE SEC_OID_PRE START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER NUEVO_OID_PRE
BEFORE INSERT ON PRESTAMOS
FOR EACH ROW
    BEGIN
        SELECT SEC_OID_PRE.NEXTVAL INTO :NEW.OID_PRE FROM DUAL;
END NUEVO_OID_PRE;

DROP SEQUENCE SEC_OID_MPR;
CREATE SEQUENCE SEC_OID_MPR START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER NUEVO_OID_MPR
BEFORE INSERT ON MATERIALES_PRESTADOS
FOR EACH ROW
    BEGIN
        SELECT SEC_OID_MPR.NEXTVAL INTO :NEW.OID_MPR FROM DUAL;
END NUEVO_OID_MPR;


DROP SEQUENCE SEC_OID_ALJ;
CREATE SEQUENCE SEC_OID_ALJ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER NUEVO_OID_ALJ
BEFORE INSERT ON ALOJAMIENTOS
FOR EACH ROW
    BEGIN
        SELECT SEC_OID_ALJ.NEXTVAL INTO :NEW.OID_ALJ FROM DUAL;
END NUEVO_OID_ALJ;


DROP SEQUENCE SEC_OID_EST;
CREATE SEQUENCE SEC_OID_EST START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER NUEVO_OID_EST
BEFORE INSERT ON ESTANCIAS
FOR EACH ROW
    BEGIN
        SELECT SEC_OID_EST.NEXTVAL INTO :NEW.OID_EST FROM DUAL;
END NUEVO_OID_EST;


