DROP TABLE USUARIOS_BD;
DROP TABLE USUARIOS;

CREATE TABLE  USUARIOS (
            DNI   VARCHAR2(50 BYTE) NOT NULL,
            NOMBRE VARCHAR2(50 BYTE) NOT NULL,
            APELLIDOS VARCHAR2(50 BYTE) NOT NULL,
            OBSERVACIONES VARCHAR2(200 BYTE),
            CONTACTO      VARCHAR2(50 BYTE) NOT NULL,
            MOTIVO_INGRESO VARCHAR2(200 BYTE)  NOT NULL,
            ESTADO_PSICOLOGICO VARCHAR2(200 BYTE)  NOT NULL,
            ESTADO_MEDICO VARCHAR2(200 BYTE)  NOT NULL,
            SANCIONESOPREMIOS NUMBER(10),
            
        PRIMARY KEY(DNI)
);

DROP TABLE ACTIVIDADES;

CREATE TABLE ACTIVIDADES (

            OID_ACT NUMBER(10) NOT NULL,
            LUGAR VARCHAR2(50 BYTE) NOT NULL,
            FECHA DATE NOT NULL,
            NUMERO_ASISTENTES NUMBER(10),
            CALIFICACIONES VARCHAR2(200 BYTE),
            
            PRIMARY KEY(OID_ACT)
);

DROP TABLE INSCRIPCIONES;

CREATE TABLE INSCRIPCIONES (

        OID_INS NUMBER(10) NOT NULL,
        DNI VARCHAR2(50 BYTE) NOT NULL,
        OID_ACT NUMBER(10) NOT NULL,
        PRIMARY KEY(OID_INS),
        FOREIGN KEY(DNI) REFERENCES USUARIOS,
        FOREIGN KEY(OID_ACT) REFERENCES ACTIVIDADES

);
DROP TABLE CITAS_MEDICAS;

CREATE TABLE CITAS_MEDICAS (

        OID_CM NUMBER(10) NOT NULL,
        DNI VARCHAR2(50 BYTE) NOT NULL,
        DOCTOR VARCHAR2(50 BYTE) NOT NULL,
        FECHA DATE NOT NULL,
        LUGAR VARCHAR2(50 BYTE) NOT NULL,
        
        PRIMARY KEY(OID_CM),
        FOREIGN KEY(DNI) REFERENCES USUARIOS
);

DROP TABLE INFROMES;

CREATE TABLE INFORMES (
    
    OID_INF NUMBER(10) NOT NULL,
    OID_CM NUMBER(10) NOT NULL,
    DNI VARCHAR2(50 BYTE) NOT NULL,
    TIPO VARCHAR2(50 BYTE) NOT NULL,
    RESPONSABLE VARCHAR2(50 BYTE) NOT NULL,
    FECHA DATE NOT NULL,
    LUGAR VARCHAR2(50 BYTE) NOT NULL,
    OBSERVACIONES LONG,
    
    PRIMARY KEY(OID_INF),
    FOREIGN KEY(OID_CM) REFERENCES CITAS_MEDICAS,
    FOREIGN KEY(DNI) REFERENCES USUARIOS

);

DROP TABLE PRESTAMOS;

CREATE TABLE PRESTAMOS(
    
    OID_PRE NUMBER(10) NOT NULL,
    DNI VARCHAR2(50 BYTE) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    DEVOLUCION VARCHAR2(1 BYTE) CHECK((DEVOLUCION='T')OR(DEVOLUCION='F')),
    NOMBRE_ENCARGADO VARCHAR2(50 BYTE),
    
    PRIMARY KEY(OID_PRE),
    FOREIGN KEY(DNI) REFERENCES USUARIOS
    
);

DROP TABLE MATERIALES_PRESTADOS;

CREATE TABLE MATERIALES_PRESTADOS(

        OID_MPR NUMBER(10) NOT NULL,
        NOMBRE VARCHAR2(50 BYTE),
        DISPONIBILIDAD VARCHAR2(1 BYTE) CHECK((DISPONIBILIDAD= 'T')OR(DISPONIBILIDAD= 'F')),
        ESTADO_DEVOLUCION VARCHAR2(50 BYTE) CHECK((ESTADO_DEVOLUCION IN('BIEN', 'MAL'))),
        CANTIDAD VARCHAR2(50 BYTE),
        TIPO VARCHAR2(50 BYTE),
        
        PRIMARY KEY(OID_MPR)
    
);

DROP TABLE UNIDADES;

CREATE TABLE UNIDADES(
    
    OID_PRE NUMBER(10) NOT NULL,
    OID_MPR NUMBER(10) NOT NULL,
    CODIGO_IDENTIFICACION VARCHAR2(50 BYTE) NOT NULL,
    ESTADO_EJEMPLAR VARCHAR2(50 BYTE) CHECK((ESTADO_EJEMPLAR='BUENO')OR(ESTADO_EJEMPLAR='MALO')),
    
    PRIMARY KEY(CODIGO_IDENTIFICACION),
    FOREIGN KEY(OID_PRE) REFERENCES PRESTAMOS,
    FOREIGN KEY(OID_MPR) REFERENCES MATERIALES_PRESTADOS


);

DROP TABLE ALOJAMIENTOS;

CREATE TABLE ALOJAMIENTOS(
        
        OID_ALJ NUMBER(10) NOT NULL,
        UBICACION VARCHAR2(50 BYTE),
        DIRECCION VARCHAR2(50 BYTE),
        RESIDENTES VARCHAR2(200 BYTE),
        NUMERO_RESIDENTES NUMBER(10),
        NUMERO_HABITACION NUMBER(10),
        DISPONIBILIDAD VARCHAR2(1 BYTE) CHECK((DISPONIBILIDAD='T')OR(DISPONIBILIDAD='F')),
        
        PRIMARY KEY(OID_ALJ)
        
);

DROP TABLE ESTANCIAS;

CREATE TABLE ESTANCIAS(

    OID_EST NUMBER(10) NOT NULL,
    DNI VARCHAR2(50 BYTE) NOT NULL,
    OID_ALJ NUMBER(10) NOT NULL,
    FECHA_ENTRADA DATE NOT NULL,
    FECHA_SALIDA DATE,
    
    PRIMARY KEY(OID_EST),
    FOREIGN KEY(DNI) REFERENCES USUARIOS,
    FOREIGN KEY(OID_ALJ) REFERENCES ALOJAMIENTOS

);

